"""products

Revision ID: 1e36f5cd5f7f
Revises: c4ca8dad63bb
Create Date: 2025-08-24 11:20:58.174798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e36f5cd5f7f'
down_revision = 'c4ca8dad63bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('order_item_product_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_orderitem_style_variant_id'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_orderitem_color_variant_id'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_orderitem_variant_id'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_orderitem_size_variant_id'), type_='foreignkey')
        batch_op.create_foreign_key('fk_orderitem_variant_id', 'product_variant', ['variant_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_orderitem_size_variant_id', 'product_variant', ['size_variant_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_orderitem_style_variant_id', 'product_variant', ['style_variant_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'product', ['product_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_orderitem_color_variant_id', 'product_variant', ['color_variant_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('replacement_order_item', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_replacementorderitem_style_variant_id'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('replacement_order_item_product_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_replacementorderitem_color_variant_id'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_replacementorderitem_size_variant_id'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_replacementorderitem_variant_id'), type_='foreignkey')
        batch_op.create_foreign_key('fk_replacementorderitem_size_variant_id', 'product_variant', ['size_variant_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_replacementorderitem_variant_id', 'product_variant', ['variant_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_replacementorderitem_style_variant_id', 'product_variant', ['style_variant_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'product', ['product_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_replacementorderitem_color_variant_id', 'product_variant', ['color_variant_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replacement_order_item', schema=None) as batch_op:
        batch_op.drop_constraint('fk_replacementorderitem_color_variant_id', type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('fk_replacementorderitem_style_variant_id', type_='foreignkey')
        batch_op.drop_constraint('fk_replacementorderitem_variant_id', type_='foreignkey')
        batch_op.drop_constraint('fk_replacementorderitem_size_variant_id', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_replacementorderitem_variant_id'), 'product_variant', ['variant_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_replacementorderitem_size_variant_id'), 'product_variant', ['size_variant_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_replacementorderitem_color_variant_id'), 'product_variant', ['color_variant_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('replacement_order_item_product_id_fkey'), 'product', ['product_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_replacementorderitem_style_variant_id'), 'product_variant', ['style_variant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orderitem_color_variant_id', type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('fk_orderitem_style_variant_id', type_='foreignkey')
        batch_op.drop_constraint('fk_orderitem_size_variant_id', type_='foreignkey')
        batch_op.drop_constraint('fk_orderitem_variant_id', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_orderitem_size_variant_id'), 'product_variant', ['size_variant_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_orderitem_variant_id'), 'product_variant', ['variant_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_orderitem_color_variant_id'), 'product_variant', ['color_variant_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_orderitem_style_variant_id'), 'product_variant', ['style_variant_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('order_item_product_id_fkey'), 'product', ['product_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
