"""Add product_id to OrderItem for products without variants

Revision ID: 3fa43e62c271
Revises: 8b30586b653b
Create Date: 2025-08-16 00:52:24.990020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fa43e62c271'
down_revision = '8b30586b653b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('employee_national_id_key'), type_='unique')

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'product', ['product_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('product_id')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('employee_national_id_key'), ['national_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
