"""Add indexes for performance

Revision ID: 4133dd121677
Revises: remove_can_clear_database
Create Date: 2025-09-10 11:39:41.102596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4133dd121677'
down_revision = 'remove_can_clear_database'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_phone'), ['phone'], unique=False)

    with op.batch_alter_table('customer_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_log_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_log_type'), ['type'], unique=False)

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_date'), ['date'], unique=False)

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_invoice_number'), ['invoice_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_supplier_id'), ['supplier_id'], unique=False)

    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issue_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_issue_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_issue_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_issue_state'), ['state'], unique=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_tracking_number'), ['tracking_number'], unique=False)

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_item_order_id'), ['order_id'], unique=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_name'), ['name'], unique=False)

    with op.batch_alter_table('replacement_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_replacement_order_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_replacement_order_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_replacement_order_original_order_id'), ['original_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_replacement_order_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replacement_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_replacement_order_status'))
        batch_op.drop_index(batch_op.f('ix_replacement_order_original_order_id'))
        batch_op.drop_index(batch_op.f('ix_replacement_order_date'))
        batch_op.drop_index(batch_op.f('ix_replacement_order_customer_id'))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_name'))
        batch_op.drop_index(batch_op.f('ix_product_is_deleted'))

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_item_order_id'))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_tracking_number'))
        batch_op.drop_index(batch_op.f('ix_order_status'))
        batch_op.drop_index(batch_op.f('ix_order_date'))
        batch_op.drop_index(batch_op.f('ix_order_customer_id'))

    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issue_state'))
        batch_op.drop_index(batch_op.f('ix_issue_order_id'))
        batch_op.drop_index(batch_op.f('ix_issue_customer_id'))
        batch_op.drop_index(batch_op.f('ix_issue_created_at'))

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_invoice_date'))

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_date'))

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_is_active'))

    with op.batch_alter_table('customer_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_log_type'))
        batch_op.drop_index(batch_op.f('ix_customer_log_timestamp'))

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_phone'))

    # ### end Alembic commands ###
