"""Initial migration with all models

Revision ID: 42dbddd2252d
Revises: 
Create Date: 2025-08-04 22:41:22.633233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42dbddd2252d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('governorate', sa.String(length=100), nullable=True),
    sa.Column('address_details', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('national_id', sa.String(length=14), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('salary', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('can_view_customers', sa.Boolean(), nullable=True),
    sa.Column('can_add_customers', sa.Boolean(), nullable=True),
    sa.Column('can_edit_customers', sa.Boolean(), nullable=True),
    sa.Column('can_delete_customers', sa.Boolean(), nullable=True),
    sa.Column('can_view_customer_orders', sa.Boolean(), nullable=True),
    sa.Column('can_view_customer_logs', sa.Boolean(), nullable=True),
    sa.Column('can_view_customer_profile', sa.Boolean(), nullable=True),
    sa.Column('can_add_customer_logs', sa.Boolean(), nullable=True),
    sa.Column('can_delete_customer_logs', sa.Boolean(), nullable=True),
    sa.Column('can_view_products', sa.Boolean(), nullable=True),
    sa.Column('can_add_products', sa.Boolean(), nullable=True),
    sa.Column('can_edit_products', sa.Boolean(), nullable=True),
    sa.Column('can_delete_products', sa.Boolean(), nullable=True),
    sa.Column('can_restore_products', sa.Boolean(), nullable=True),
    sa.Column('can_delete_all_products', sa.Boolean(), nullable=True),
    sa.Column('can_view_orders', sa.Boolean(), nullable=True),
    sa.Column('can_add_orders', sa.Boolean(), nullable=True),
    sa.Column('can_edit_orders', sa.Boolean(), nullable=True),
    sa.Column('can_delete_orders', sa.Boolean(), nullable=True),
    sa.Column('can_update_order_status', sa.Boolean(), nullable=True),
    sa.Column('can_update_tracking', sa.Boolean(), nullable=True),
    sa.Column('can_view_orders_by_status', sa.Boolean(), nullable=True),
    sa.Column('can_view_replacements', sa.Boolean(), nullable=True),
    sa.Column('can_add_replacements', sa.Boolean(), nullable=True),
    sa.Column('can_edit_replacements', sa.Boolean(), nullable=True),
    sa.Column('can_view_replacements_by_state', sa.Boolean(), nullable=True),
    sa.Column('can_view_fees', sa.Boolean(), nullable=True),
    sa.Column('can_edit_fees', sa.Boolean(), nullable=True),
    sa.Column('can_delete_fees', sa.Boolean(), nullable=True),
    sa.Column('can_view_employees', sa.Boolean(), nullable=True),
    sa.Column('can_add_employees', sa.Boolean(), nullable=True),
    sa.Column('can_edit_employees', sa.Boolean(), nullable=True),
    sa.Column('can_delete_employees', sa.Boolean(), nullable=True),
    sa.Column('can_view_employee_logs', sa.Boolean(), nullable=True),
    sa.Column('can_manage_employee_salary', sa.Boolean(), nullable=True),
    sa.Column('can_view_employee_activity', sa.Boolean(), nullable=True),
    sa.Column('can_view_statistics', sa.Boolean(), nullable=True),
    sa.Column('can_view_reports', sa.Boolean(), nullable=True),
    sa.Column('can_view_suppliers', sa.Boolean(), nullable=True),
    sa.Column('can_add_suppliers', sa.Boolean(), nullable=True),
    sa.Column('can_edit_suppliers', sa.Boolean(), nullable=True),
    sa.Column('can_delete_suppliers', sa.Boolean(), nullable=True),
    sa.Column('can_view_supplier_invoices', sa.Boolean(), nullable=True),
    sa.Column('can_view_supplier_history', sa.Boolean(), nullable=True),
    sa.Column('can_pay_supplier_debt', sa.Boolean(), nullable=True),
    sa.Column('can_view_invoices', sa.Boolean(), nullable=True),
    sa.Column('can_add_invoices', sa.Boolean(), nullable=True),
    sa.Column('can_edit_invoices', sa.Boolean(), nullable=True),
    sa.Column('can_delete_invoices', sa.Boolean(), nullable=True),
    sa.Column('can_view_invoice_details', sa.Boolean(), nullable=True),
    sa.Column('can_view_expenses', sa.Boolean(), nullable=True),
    sa.Column('can_add_expenses', sa.Boolean(), nullable=True),
    sa.Column('can_edit_expenses', sa.Boolean(), nullable=True),
    sa.Column('can_delete_expenses', sa.Boolean(), nullable=True),
    sa.Column('can_view_operational_expenses', sa.Boolean(), nullable=True),
    sa.Column('can_view_fixed_assets', sa.Boolean(), nullable=True),
    sa.Column('can_clear_database', sa.Boolean(), nullable=True),
    sa.Column('can_view_activity_log', sa.Boolean(), nullable=True),
    sa.Column('can_manage_reminders', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('national_id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    op.create_table('governorate_fee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('purchase_price', sa.Float(), nullable=False),
    sa.Column('wholesale_price', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('has_size', sa.Boolean(), nullable=True),
    sa.Column('has_color', sa.Boolean(), nullable=True),
    sa.Column('has_style', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('total_debt', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('entity_name', sa.String(length=200), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_login_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('login_time', sa.DateTime(), nullable=True),
    sa.Column('logout_time', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('receipt_number', sa.String(length=100), nullable=True),
    sa.Column('supplier', sa.String(length=100), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('paid_amount', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('delivery_fees', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('replacement_tracking', sa.String(length=100), nullable=True),
    sa.Column('sender_name', sa.String(length=100), nullable=True),
    sa.Column('sender_phone', sa.String(length=20), nullable=True),
    sa.Column('sender_address', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=50), nullable=False),
    sa.Column('variant_name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='fk_productvariant_product_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salary_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('reminder_time', sa.DateTime(), nullable=True),
    sa.Column('reminder_duration', sa.Integer(), nullable=True),
    sa.Column('reminder_duration_type', sa.String(length=20), nullable=True),
    sa.Column('follow_up_reason', sa.Text(), nullable=True),
    sa.Column('is_dismissed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='fk_customer_log_customer_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name='fk_customer_log_order_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('purchase_price', sa.Float(), nullable=False),
    sa.Column('selling_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('size_variant_id', sa.Integer(), nullable=True),
    sa.Column('color_variant_id', sa.Integer(), nullable=True),
    sa.Column('style_variant_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['color_variant_id'], ['product_variant.id'], name='fk_orderitem_color_variant_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['size_variant_id'], ['product_variant.id'], name='fk_orderitem_size_variant_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['style_variant_id'], ['product_variant.id'], name='fk_orderitem_style_variant_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variant.id'], name='fk_orderitem_variant_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_item')
    op.drop_table('issue')
    op.drop_table('invoice_item')
    op.drop_table('customer_log')
    op.drop_table('salary_transaction')
    op.drop_table('product_variant')
    op.drop_table('order')
    op.drop_table('invoice')
    op.drop_table('expense')
    op.drop_table('employee_login_log')
    op.drop_table('employee_activity_log')
    op.drop_table('supplier')
    op.drop_table('product')
    op.drop_table('governorate_fee')
    op.drop_table('employee')
    op.drop_table('customer')
    # ### end Alembic commands ###
