"""add_sales_commission_and_employee_to_orders

Revision ID: 612c49e763e9
Revises: e28ae3438199
Create Date: 2025-12-02 13:42:31.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '612c49e763e9'
down_revision = 'e28ae3438199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sales_commission_percentage', sa.Float(), nullable=False, server_default='0'))

    # إزالة server_default بعد إضافة العمود لجعل القيمة الافتراضية في الكود فقط
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('sales_commission_percentage', server_default=None)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_order_employee_id'), ['employee_id'], unique=False)
        batch_op.create_foreign_key('fk_order_employee_id', 'employee', ['employee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('fk_order_employee_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_order_employee_id'))
        batch_op.drop_column('employee_id')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('sales_commission_percentage')

    # ### end Alembic commands ###
