"""Remove sender fields from ReplacementOrder and Issue models

Revision ID: 698205474ba0
Revises: 9a3d35e282b6
Create Date: 2025-08-17 23:31:14.320946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '698205474ba0'
down_revision = '9a3d35e282b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.drop_column('sender_address')
        batch_op.drop_column('sender_phone')
        batch_op.drop_column('sender_name')

    with op.batch_alter_table('replacement_order', schema=None) as batch_op:
        batch_op.drop_column('sender_address')
        batch_op.drop_column('sender_phone')
        batch_op.drop_column('sender_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replacement_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sender_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sender_address', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('sender_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('sender_address', sa.VARCHAR(length=200), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
