"""add replacement_order_id field

Revision ID: 8b30586b653b
Revises: d2db92f7ff74
Create Date: 2025-08-04 23:55:17.873102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b30586b653b'
down_revision = 'd2db92f7ff74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('replacement_tracking', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('replacement_order_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'order', ['replacement_order_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('replacement_order_id')
        batch_op.drop_column('replacement_tracking')

    # ### end Alembic commands ###
