"""Add accounting fields to replacement orders

Revision ID: 9a3d35e282b6
Revises: b9d5d5df1099
Create Date: 2025-08-17 23:12:05.303749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a3d35e282b6'
down_revision = 'b9d5d5df1099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replacement_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('damaged_products_loss', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('customer_refund_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('delivery_fees_loss', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_loss', sa.Float(), nullable=True))

    with op.batch_alter_table('replacement_order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_damaged', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('purchase_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('damage_loss', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replacement_order_item', schema=None) as batch_op:
        batch_op.drop_column('damage_loss')
        batch_op.drop_column('purchase_price')
        batch_op.drop_column('is_damaged')

    with op.batch_alter_table('replacement_order', schema=None) as batch_op:
        batch_op.drop_column('total_loss')
        batch_op.drop_column('delivery_fees_loss')
        batch_op.drop_column('customer_refund_amount')
        batch_op.drop_column('damaged_products_loss')

    # ### end Alembic commands ###
