"""add capital snapshots table

Revision ID: xyz123capital456
Revises: jkl456mno789
Create Date: 2026-01-17 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'xyz123capital456'
down_revision = 'jkl456mno789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capital_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('fixed_assets_value', sa.Float(), nullable=False),
    sa.Column('pending_orders_value', sa.Float(), nullable=False),
    sa.Column('stock_value', sa.Float(), nullable=False),
    sa.Column('total_capital', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name='_capital_year_month_uc')
    )
    op.create_index(op.f('ix_capital_snapshots_month'), 'capital_snapshots', ['month'], unique=False)
    op.create_index(op.f('ix_capital_snapshots_year'), 'capital_snapshots', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_capital_snapshots_year'), table_name='capital_snapshots')
    op.drop_index(op.f('ix_capital_snapshots_month'), table_name='capital_snapshots')
    op.drop_table('capital_snapshots')
    # ### end Alembic commands ###
