"""Update replacement order system

Revision ID: b9d5d5df1099
Revises: 3fa43e62c271
Create Date: 2025-08-17 22:21:12.299416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9d5d5df1099'
down_revision = '3fa43e62c271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('order_replacement_order_id_fkey'), type_='foreignkey')
        batch_op.drop_column('sender_address')
        batch_op.drop_column('replacement_order_id')
        batch_op.drop_column('sender_phone')
        batch_op.drop_column('replacement_tracking')
        batch_op.drop_column('sender_name')

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('replacement_tracking', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sender_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('replacement_order_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sender_address', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('order_replacement_order_id_fkey'), 'order', ['replacement_order_id'], ['id'])

    # ### end Alembic commands ###
