"""Add

Revision ID: c4ca8dad63bb
Revises: 4497d1f33930
Create Date: 2025-08-21 18:37:23.650991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4ca8dad63bb'
down_revision = '4497d1f33930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replacement_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replacement_order', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
