"""remove replacement_tracking column

Revision ID: d2db92f7ff74
Revises: fdaa4fe8183c
Create Date: 2025-08-04 23:48:41.794641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2db92f7ff74'
down_revision = 'fdaa4fe8183c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('replacement_tracking')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('replacement_tracking', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
