"""follow up new buttons

Revision ID: ef3c6090b453
Revises: 1e36f5cd5f7f
Create Date: 2025-09-06 20:33:42.385075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef3c6090b453'
down_revision = '1e36f5cd5f7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow_up', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_contact_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('next_contact_due', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_follow_up_next_contact_due'), ['next_contact_due'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow_up', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_follow_up_next_contact_due'))
        batch_op.drop_column('next_contact_due')
        batch_op.drop_column('last_contact_at')

    # ### end Alembic commands ###
